
export interface PolicyContent {
  title: string;
  lastUpdated: string;
  sections: {
    heading: string;
    content: string | string[];
  }[];
}

export const POLICIES: Record<string, PolicyContent> = {
  'terms-conditions': {
    title: 'Terms & Conditions',
    lastUpdated: 'May 2024',
    sections: [
      {
        heading: '1. Electronic Record',
        content: 'This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.'
      },
      {
        heading: '2. Compliance',
        content: 'This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name https://kisslead.com/ (\'Website\'), including the related mobile site and mobile application (hereinafter referred to as \'Platform\').'
      },
      {
        heading: '3. Ownership',
        content: 'The Platform is owned by 9626622296, a company incorporated under the Companies Act, 1956 with its registered office at 89, NG Narayanaswamy Street, New Siddhapudur, Coimbatore - 641044 (hereinafter referred to as \'Platform Owner\', \'we\', \'us\', \'our\').'
      },
      {
        heading: '4. Usage Terms',
        content: 'Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.'
      },
      {
        heading: '5. Terms of Use Conditions',
        content: [
          'To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration.',
          'Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information offered.',
          'Your use of our Services and the Platform is solely and entirely at your own risk and discretion.',
          'The contents of the Platform and the Services are proprietary to us and are licensed to us.',
          'Unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.',
          'You agree to pay us the charges associated with availing the Services.',
          'You agree not to use the Platform for any purpose that is unlawful or forbidden by these Terms.',
          'The Services may contain links to other third party websites governed by their own policies.',
          'Upon initiating a transaction for availing the Services you are entering into a legally binding and enforceable contract.'
        ]
      },
      {
        heading: '6. Indemnification',
        content: 'You shall indemnify and hold harmless Platform Owner, its affiliates, group companies and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney\'s fees, made by any third party due to or arising out of Your breach of these Terms of Use.'
      },
      {
        heading: '7. Governing Law',
        content: 'These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising shall be subject to exclusive jurisdiction of the courts.'
      }
    ]
  },
  'privacy-policy': {
    title: 'Privacy Policy',
    lastUpdated: 'May 2024',
    sections: [
      {
        heading: 'Introduction',
        content: 'This Privacy Policy describes how 9626622296 and its affiliates (collectively "9626622296, we, our, us") collect, use, share, protect or otherwise process your information/ personal data through our website https://kisslead.com/ (hereinafter referred to as Platform). We do not offer any product/service under this Platform outside India and your personal data will primarily be stored and processed in India.'
      },
      {
        heading: 'Collection of Data',
        content: 'We collect your personal data when you use our Platform, services or otherwise interact with us. This includes but is not limited to name, date of birth, address, telephone/mobile number, email ID and/or any such information shared as proof of identity or address. Sensitive personal data like bank account or card information may be collected with your consent.'
      },
      {
        heading: 'Usage of Data',
        content: 'We use personal data to provide the services you request. To the extent we use your personal data to market to you, we will provide you the ability to opt-out. We use data to resolve disputes, troubleshoot problems, detect and protect against error, fraud and other criminal activity, and enforce our terms and conditions.'
      },
      {
        heading: 'Sharing of Data',
        content: 'We may share your personal data internally within our group entities and affiliates. We may disclose personal data to third parties such as business partners and service providers to provide you access to our services, to comply with legal obligations, or to facilitate marketing and advertising activities.'
      },
      {
        heading: 'Security Precautions',
        content: 'To protect your personal data from unauthorised access or disclosure, we adopt reasonable security practices and procedures. Once your information is in our possession, we adhere to security guidelines to protect it, though transmission over the internet is not completely secure.'
      },
      {
        heading: 'Data Deletion and Retention',
        content: 'You have an option to delete your account by visiting your profile settings. We retain your personal data information for a period no longer than is required for the purpose for which it was collected or as required under any applicable law.'
      },
      {
        heading: 'Consent',
        content: 'By visiting our Platform or providing your information, you consent to the collection, use, storage, disclosure and otherwise processing of your information in accordance with this Privacy Policy.'
      }
    ]
  },
  'refund-cancellation': {
    title: 'Refund and Cancellation Policy',
    lastUpdated: 'May 2024',
    sections: [
      {
        heading: 'Cancellation Policy',
        content: 'Cancellations will only be considered if the request is made within 3 days of placing the order. However, cancellation requests may not be entertained if the orders have been communicated to sellers/merchants and they have initiated the process of shipping them, or the product is out for delivery.'
      },
      {
        heading: 'Perishable Items',
        content: '9626622296 does not accept cancellation requests for perishable items like flowers, eatables, etc. However, a refund/replacement can be made if the user establishes that the quality of the product delivered is not good.'
      },
      {
        heading: 'Damaged or Defective Items',
        content: 'In case of receipt of damaged or defective items, please report to our customer service team. This should be reported within 3 days of receipt of products. The request will be entertained once the seller/merchant has checked and determined the same.'
      },
      {
        heading: 'Refund Processing',
        content: 'In case of any refunds approved by 9626622296, it will take 3 days for the refund to be processed to you.'
      }
    ]
  },
  'return-policy': {
    title: 'Return Policy',
    lastUpdated: 'May 2024',
    sections: [
      {
        heading: 'Eligibility for Returns',
        content: 'We offer refund / exchange within first 3 days from the date of your purchase. If 3 days have passed since your purchase, you will not be offered a return, exchange or refund of any kind.'
      },
      {
        heading: 'Condition for Return',
        content: [
          'The purchased item should be unused and in the same condition as you received it.',
          'The item must have original packaging.',
          'If the item was purchased on a sale, it may not be eligible for return/exchange.'
        ]
      },
      {
        heading: 'Exemptions',
        content: 'Certain categories of products/items are exempted from returns or refunds. These categories will be identified to you at the time of purchase.'
      },
      {
        heading: 'Process',
        content: 'Once your returned product is received and inspected, we will send you an email notification. If approved after quality check, your request will be processed in accordance with our policies.'
      }
    ]
  },
  'shipping-policy': {
    title: 'Shipping Policy',
    lastUpdated: 'May 2024',
    sections: [
      {
        heading: 'Shipping Methods',
        content: 'The orders for the user are shipped through registered domestic courier companies and/or speed post only.'
      },
      {
        heading: 'Delivery Timeline',
        content: 'Orders are shipped within 3 days from the date of the order and/or payment or as per the delivery date agreed at the time of order confirmation, subject to courier company / post office norms.'
      },
      {
        heading: 'Liability',
        content: 'Platform Owner shall not be liable for any delay in delivery by the courier company / postal authority. Delivery of all orders will be made to the address provided by the buyer at the time of purchase.'
      },
      {
        heading: 'Confirmation and Costs',
        content: 'Delivery of our services will be confirmed on your email ID as specified at the time of registration. If there are any shipping cost(s) levied, the same is not refundable.'
      }
    ]
  }
};
